### ISSUE TITLE
ACMW Bootstrap

### ISSUE THREAD

**Issue by VinayakTekade** [aravindvnair99/FACE-Amrita-Bengaluru#166]
**Describe the bug**
Bootstrap 4 code written with Bootstrap 3 CDN in all the pages.

**Comment by aravindvnair99** [comment]
@VinayakTekade Mention files and line numbers for the same.

**Comment by VinayakTekade** [comment]
Bootstrap 3 CDN is added here
https://github.com/aravindvnair99/FACE-Amrita-Bengaluru/blob/master/functions/views/ACMW/index.ejs#L8

These are supported in Bootstrap 4
https://github.com/aravindvnair99/FACE-Amrita-Bengaluru/blob/master/functions/views/ACMW/index.ejs#L553
https://github.com/aravindvnair99/FACE-Amrita-Bengaluru/blob/master/functions/views/ACMW/events.ejs#L34
And other similar spacing classes from Bootstrap 4.

Apart from them using Bootstrap 3 makes our website vulnerable to XSS attacks and CSRF attacks.

**Comment by aravindvnair99** [comment]
> Bootstrap 3 CDN is added here
> https://github.com/aravindvnair99/FACE-Amrita-Bengaluru/blob/master/functions/views/ACMW/index.ejs#L8
> 
> These are supported in Bootstrap 4
> https://github.com/aravindvnair99/FACE-Amrita-Bengaluru/blob/master/functions/views/ACMW/index.ejs#L553
> https://github.com/aravindvnair99/FACE-Amrita-Bengaluru/blob/master/functions/views/ACMW/events.ejs#L34
> And other similar spacing classes from Bootstrap 4.
> 
> Apart from them using Bootstrap 3 makes our website vulnerable to XSS attacks and CSRF attacks.

1. I couldn't find much Bootstrap 4 or unused classes. Just a few things here and there on ACM and ACMW pages. Moreover, there are no negative effects of having unused classes as it just sits as an unused selector. CSS selectively modifies content based on HTML classes. "CSS classes" are a misnomer. So it wouldn't be worth the time to clean up unused classes. If you all wish to, you can try running something like [this](https://gist.github.com/kdzwinel/426a0f76f113643fa285), verify if it's being used anywhere and clean up. But again, is it worth the time? There won't be any active development henceforth apart from updating team pages every year. So it's okay to leave them there.

2. Merely using Bootstrap 3 doesn't make websites or web apps vulnerable to XSS and/or CSRF attacks. We aren't vulnerable to any of them either because of how the website works. If you submit a POC, we can discuss further on this.

@VinayakTekade Let me know your thoughts. I shall be closing the issue if we don't have any bugs here.

**Comment by VinayakTekade** [comment]
Okay, then create a separate issue for making it screen responsive.

**Comment by VinayakTekade** [comment]
Feel free to reopen this issue, if there are any further queries.
